import type { Metadata } from "next";
import "./globals.css";
import 'smarthr-ui/smarthr-ui.css'
import { IntlProvider } from "smarthr-ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <IntlProvider locale="ja">
          {children}
        </IntlProvider>
      </body>
    </html>
  );
}
